apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}-svc
spec:
  selector:
     {{- range $key, $val := .Values.deploymentlabels }}
     {{ $key }}: {{ $val | quote }}
     {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}