apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: service-ip
        image: 987313237108.dkr.ecr.eu-west-1.amazonaws.com/server_ip:latest
        ports:
        - containerPort: 8000